"""Utility functions for preparing METRIC input matrices and LDA priors.

This module converts DMB-level unmethylated-read count matrices into
Gensim-compatible corpora and builds the guided LDA eta matrix used by METRIC.
"""

from __future__ import annotations

import datetime
import json
import os
from pathlib import Path
from typing import Iterable, Optional

import gensim
import numpy as np
import pandas as pd
from gensim.corpora.dictionary import Dictionary
from scipy.sparse import csr_matrix


MARKER_COLUMNS = [
    "chr",
    "start",
    "end",
    "startCpG",
    "endCpG",
    "group",
    "name",
    "lenCpG",
    "bp",
    "tg_mean",
    "bg_mean",
    "delta_means",
    "delta_quants",
    "delta_maxmin",
    "ttest",
    "direction",
]

DEFAULT_EXEMPT_GROUPS = [
    "Pancreas",
    "Breast",
    "Liver",
    "Uterus",
    "Nerve",
    "Kidney",
    "Pituitary",
    "Ovary",
    "Stom",
]


def get_file_name(filepath: str | os.PathLike) -> str:
    """Return the filename without extension."""
    return Path(filepath).stem


# Backward-compatible alias for older scripts.
getFileName = get_file_name


def _read_marker_info(marker_info_file: str | os.PathLike) -> pd.DataFrame:
    """Read the marker annotation table generated by wgbstools find_markers."""
    marker_info = pd.read_csv(marker_info_file, sep="\t", header=None)
    marker_info.columns = MARKER_COLUMNS
    marker_info["group"] = marker_info["group"].astype(str).str.capitalize()
    return marker_info.sort_values(by="group", ascending=True).reset_index(drop=True)


def _read_sample_group(sample_group_file: str | os.PathLike) -> pd.DataFrame:
    """Read sample metadata and normalize group names."""
    sample_group = pd.read_csv(sample_group_file, header=0)
    required = {"name", "group"}
    missing = required.difference(sample_group.columns)
    if missing:
        raise ValueError(f"Sample group file is missing required columns: {sorted(missing)}")
    sample_group["group"] = sample_group["group"].astype(str).str.capitalize()
    return sample_group.sort_values(by="group", ascending=True).reset_index(drop=True)


def _read_count_matrix(file_path: str | os.PathLike) -> pd.DataFrame:
    """Read a DMB count matrix and build a genomic-region marker name."""
    data = pd.read_csv(file_path, sep="\t", header=0)
    required = {"chr", "start", "end"}
    missing = required.difference(data.columns)
    if missing:
        raise ValueError(f"Count matrix is missing required columns: {sorted(missing)}")
    data["name"] = data["chr"].astype(str) + ":" + data["start"].astype(str) + "-" + data["end"].astype(str)
    return data


def _get_sample_matrix(data: pd.DataFrame, sample_group: pd.DataFrame) -> pd.DataFrame:
    """Extract and order the marker-by-sample matrix using sample_group['name']."""
    sample_names = sample_group["name"].tolist()
    missing_samples = [name for name in sample_names if name not in data.columns]
    if missing_samples:
        raise ValueError(
            "The count matrix does not contain all samples listed in the sample group file. "
            f"Missing examples: {missing_samples[:5]}"
        )
    return data.loc[:, sample_names]


def _scale_global_minmax(
    matrix: pd.DataFrame,
    new_min: int = 1000,
    new_max: int = 1_000_000,
) -> pd.DataFrame:
    """Scale nonzero values globally and keep missing/no-read markers as zero.

    Zero values in the U-count matrix are treated as no unmethylated-read evidence
    for the corresponding marker and are temporarily converted to NaN before
    min-max scaling. Missing values are restored to zero after scaling.
    """
    scaled = matrix.copy()
    scaled = scaled.replace(0, np.nan)

    min_val = scaled.min().min()
    max_val = scaled.max().max()

    if pd.isna(min_val) or pd.isna(max_val):
        raise ValueError("The input matrix contains no nonzero values to scale.")

    if max_val == min_val:
        scaled = scaled.where(scaled.isna(), new_min)
    else:
        scaled = (((scaled - min_val) / (max_val - min_val)) * (new_max - new_min)) + new_min

    return scaled.round(0).fillna(0).astype(int)


def _scale_column_minmax(
    matrix: pd.DataFrame,
    new_min: int = 1000,
    new_max: int = 1_000_000,
) -> pd.DataFrame:
    """Scale each sample column independently and keep missing/no-read values as zero."""
    scaled = matrix.copy().replace(0, np.nan)

    def scale_column(col: pd.Series) -> pd.Series:
        min_val = col.min()
        max_val = col.max()
        if pd.isna(min_val) or pd.isna(max_val):
            return col
        if max_val == min_val:
            return col.where(col.isna(), new_min)
        return ((col - min_val) / (max_val - min_val)) * (new_max - new_min) + new_min

    scaled = scaled.apply(scale_column, axis=0)
    return scaled.round(0).fillna(0).astype(int)


def _matrix_to_gensim_corpus(matrix: pd.DataFrame) -> tuple[gensim.matutils.Sparse2Corpus, Dictionary]:
    """Convert a marker-by-sample matrix to a Gensim corpus and dictionary."""
    sparse_matrix = csr_matrix(matrix.values.astype(np.float64))
    corpus = gensim.matutils.Sparse2Corpus(sparse_matrix)
    dictionary = Dictionary([matrix.index.to_list()])
    return corpus, dictionary


def get_top_n_per_group_v2(
    df: pd.DataFrame,
    group_col: str,
    sort_col: str,
    top_N: int,
    exempt_groups: Optional[Iterable[str]] = None,
    exempt_top_n: Optional[int] = None,
) -> pd.DataFrame:
    """Select top-ranked markers within each group.

    Parameters
    ----------
    df
        Input DataFrame containing marker annotations and scores.
    group_col
        Column used to define marker groups.
    sort_col
        Column used for descending sorting within each group.
    top_N
        Number of markers retained for non-exempt groups.
    exempt_groups
        Groups for which all markers are retained, unless exempt_top_n is set.
    exempt_top_n
        Optional number of markers retained for exempt groups.

    Returns
    -------
    pandas.DataFrame
        Filtered marker table.
    """
    exempt_groups = set(exempt_groups or [])

    def select_top_n(sub_df: pd.DataFrame) -> pd.DataFrame:
        group_value = sub_df[group_col].iloc[0]
        if group_value in exempt_groups:
            if exempt_top_n is not None:
                return sub_df.nlargest(exempt_top_n, sort_col)
            return sub_df
        return sub_df.nlargest(top_N, sort_col)

    return df.groupby(group_col, group_keys=False).apply(select_top_n).reset_index(drop=True)


def generate_train_corpus(
    file_path: str | os.PathLike,
    marker_info_file: str | os.PathLike,
    sample_group_file: str | os.PathLike,
    feature_markers: Optional[Iterable[str]] = None,
    n_top_words: int = 25,
    exempt_top_n: Optional[int] = None,
    exempt_groups: Optional[Iterable[str]] = None,
) -> dict:
    """Generate the training corpus and marker metadata for METRIC.

    The training matrix is built from DMB-level U-count features. Markers are
    ranked by delta_means within each marker group, then converted to a
    marker-by-sample matrix and scaled for Gensim LDA input.
    """
    sample_group = _read_sample_group(sample_group_file)
    marker_info = _read_marker_info(marker_info_file)
    count_data = _read_count_matrix(file_path)

    merged = pd.merge(
        marker_info[["name", "group", "delta_means", "delta_quants"]],
        count_data,
        how="left",
        on="name",
    )

    selected = get_top_n_per_group_v2(
        merged,
        group_col="group",
        sort_col="delta_means",
        top_N=n_top_words,
        exempt_groups=exempt_groups if exempt_groups is not None else DEFAULT_EXEMPT_GROUPS,
        exempt_top_n=exempt_top_n,
    )

    if feature_markers is not None:
        selected = selected[selected["name"].isin(list(feature_markers))]

    dui = _get_sample_matrix(selected, sample_group)
    dui.index = selected["name"]

    if feature_markers is not None:
        dui = dui.loc[list(feature_markers)]

    marker_group = selected[["name", "group", "delta_means", "delta_quants"]].copy()
    marker_group.columns = ["marker", "group", "delta_means", "delta_quants"]
    marker_location = selected[["name", "chr", "start", "end"]].copy()

    dui_scaled = _scale_global_minmax(dui)
    corpus, dictionary = _matrix_to_gensim_corpus(dui_scaled)

    return {
        "corpus": corpus,
        "dictionary": dictionary,
        "sampleGroup": sample_group,
        "markerGroup": marker_group,
        "celltypes": marker_info["group"].unique(),
        "markers": dui_scaled.index.unique(),
        "markerLocation": marker_location,
        "DUI": dui,
        "DUI_scaled": dui_scaled,
    }


def generate_test_corpus(
    file_path: str | os.PathLike,
    marker_info_file: str | os.PathLike,
    sample_group_file: str | os.PathLike,
    feature_markers: Iterable[str],
    direction: str = "U",
    n_top_words: int = 25,
) -> dict:
    """Generate a test corpus using the marker order learned from training.

    Parameters direction and n_top_words are retained for backward compatibility.
    """
    sample_group = _read_sample_group(sample_group_file)
    marker_info = _read_marker_info(marker_info_file)
    count_data = _read_count_matrix(file_path)

    merged = pd.merge(
        marker_info[["name", "group", "delta_means"]],
        count_data,
        how="left",
        on="name",
    )

    feature_markers = list(feature_markers)
    selected = merged[merged["name"].isin(feature_markers)].copy()

    dui = _get_sample_matrix(selected, sample_group)
    dui.index = selected["name"]
    dui = dui.reindex(feature_markers)

    marker_group = selected[["name", "group"]].copy()
    marker_group.columns = ["marker", "group"]
    marker_location = selected[["name", "chr", "start", "end"]].copy()

    dui_scaled = _scale_column_minmax(dui)
    corpus, dictionary = _matrix_to_gensim_corpus(dui_scaled)

    return {
        "corpus": corpus,
        "dictionary": dictionary,
        "sampleGroup": sample_group,
        "markerGroup": marker_group,
        "markerLocation": marker_location,
        "DUI": dui,
        "DUI_scaled": dui_scaled,
    }


def generate_ETA_v2(
    markerGroup: pd.DataFrame,
    celltypes: Iterable[str],
    markers: Iterable[str],
    eta_norm: bool,
    num_topics: int,
) -> np.ndarray:
    """Build the guided LDA eta matrix from marker-group delta_quants values.

    Rows correspond to topics and columns correspond to markers. If num_topics
    is larger than the number of annotated cell types, additional low-prior
    rows are appended to allow extra latent topics.
    """
    markers = list(markers)
    celltypes = list(celltypes)

    if num_topics < len(celltypes):
        raise ValueError(
            f"num_topics ({num_topics}) must be >= the number of cell types ({len(celltypes)})."
        )

    eta = markerGroup.pivot(index="group", columns="marker", values="delta_quants").fillna(0.001)
    eta = eta.reindex(index=celltypes, columns=markers).fillna(0.001)

    n_extra_topics = num_topics - len(celltypes)
    if n_extra_topics > 0:
        extra_rows = pd.DataFrame(0.001, index=range(n_extra_topics), columns=eta.columns)
        eta = pd.concat([eta, extra_rows], ignore_index=True)

    if eta_norm:
        eta = eta.div(eta.sum(axis=0), axis=1).fillna(0.001)

    return eta.to_numpy(dtype=float) * 1000


def _resolve_existing_file(candidates: list[Path], description: str) -> Path:
    """Return the first existing file among candidates, or the first candidate if none exist."""
    for candidate in candidates:
        if candidate.exists():
            return candidate
    # Return the primary expected path so downstream error messages remain informative.
    return candidates[0]


def setInputOutputFile_v2(
    mainPath: str | os.PathLike,
    selected_id: str,
    topn: str | int = 25,
    current_time: Optional[str] = None,
    parameters: Optional[dict] = None,
) -> dict:
    """Construct input and output paths for a METRIC training run."""
    if parameters is None:
        raise ValueError("parameters must be provided.")

    n_topics = parameters["n_topics"]
    n_top_words = parameters["n_top_words"]
    topn_str = str(topn)

    work_dir = Path(mainPath)
    input_dir = work_dir / "input"

    train_sample_group_file = input_dir / f"{selected_id}.csv"
    train_set_file = input_dir / f"{selected_id}_top{topn_str}_TrainSet_countU.bed"
    test_set_file = input_dir / f"{selected_id}_top{topn_str}_TestSet_countU.bed"
    test_sample_group_file = input_dir / f"{selected_id}_testSetSampleGroup.csv"

    marker_info_file = _resolve_existing_file(
        [
            input_dir / f"Merged_Markers_top{topn_str}_deldup.bed",
            input_dir / f"Merged_Markers_Top{topn_str}_deldup.bed",
        ],
        description="marker information file",
    )

    train_prefix = get_file_name(train_set_file)
    test_prefix = get_file_name(test_set_file)

    output_dir = work_dir / "results" / f"{train_prefix}_top{n_top_words}" / f"topic_{n_topics}"
    output_dir.mkdir(parents=True, exist_ok=True)

    model_dir = output_dir / "ModelTrained"
    model_dir.mkdir(parents=True, exist_ok=True)

    files = {
        "inputDir": str(input_dir),
        "markerInfoFile": str(marker_info_file),
        "trainPrefix": train_prefix,
        "trainSampleGroupFile": str(train_sample_group_file),
        "trainSetFile": str(train_set_file),
        "testPrefix": test_prefix,
        "testSetSampleGroupFile": str(test_sample_group_file),
        "testSetFile": str(test_set_file),
        "trainMatrixFile": str(output_dir / f"{train_prefix}_DUI_matrix.xlsx"),
        "trainMarkerList": str(output_dir / f"{train_prefix}_train_marker.xlsx"),
        "top_words_save_path": str(output_dir / f"{train_prefix}_predict_top_celltype_markers.xlsx"),
        "trainSet_predict_save_path": str(output_dir / f"{train_prefix}_deconv_celltype.xlsx"),
        "testMatrixFile": str(output_dir / f"{test_prefix}_DUI_matrix.xlsx"),
        "testSet_predict_save_path": str(output_dir / f"{test_prefix}_deconv_celltype.xlsx"),
        "deconvolution_record": str(output_dir / "Deconvolution_Record.txt"),
        "outputDir": str(output_dir),
        "lda_model_save_path": str(model_dir / f"{train_prefix}_lda.model"),
        "lda_model_save_dir": str(model_dir),
    }

    parameter_path = output_dir / f"{train_prefix}_parameters.json"
    with parameter_path.open("w", encoding="utf-8") as handle:
        json.dump(parameters, handle, ensure_ascii=False, indent=4)

    files_path = output_dir / f"{train_prefix}_Files.json"
    with files_path.open("w", encoding="utf-8") as handle:
        json.dump(files, handle, ensure_ascii=False, indent=4)

    return files
